# Generated by Django 4.1.1 on 2023-03-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
