# Generated by Django 4.1.1 on 2023-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_customer_last_login_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
