# Generated by Django 4.1.1 on 2023-03-25 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_customer_options_customer_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cake')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
