# Generated by Django 4.1.1 on 2023-03-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
